spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_ums?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: mall_tiny
    password: 1233rs!@d
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6479 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）

logging:
  level:
    root: info
    com.tzf.dashboard: debug